### ISSUE TITLE
Request wildcard cert

### ISSUE THREAD

**Issue by Ne00n** [jaredhendrickson13/simple_acme_dns#7]
Hey.

Is it possible to request a wildcart cert? and if so, how?
Since I am running into issues when I specify *.test.com it throws me a reference to RFC2181 which expects test.com or such related.

Thanks.

**Comment by harshadsowani** [comment]
same requirement for me - looks like the validators.domain() returns a validation failure for any *.domainname. Are there any plans for adding support for wildcards?

**Comment by jaredhendrickson13** [comment]
Hey!

Sorry for the super late response on this. I have not been keeping up with this repo since my last commit. Currently there is no way to generate a wildcard cert. I typically don't use wildcard certificates but it would be a very valuable feature to have. When I get a chance, I can play around with code and see if I can get wildcard certificates working and publish an updated release. In the meantime, if anyone is more familiar with the Python acme module and wants to give it shot feel free to fork the repo and open a pull request. I'd gladly accept the contribution. 

Thanks!
